# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in precompiled.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"
gem "rake-compiler-dock", "1.5.0.rc1"

gem "minitest", "~> 5.0"
