# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in packaged_tarball.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rake-compiler"

gem "minitest", "~> 5.0"
gem "mini_portile2", path: "../../mini_portile"
