# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

require "rake/extensiontask"

task build: :compile

Rake::ExtensionTask.new("packaged_source") do |ext|
  ext.lib_dir = "lib/rcee/packaged_source"
end

task default: %i[clobber compile test]

CLEAN.add("{ext,lib}/**/*.{o,so}")
