name: packaged_tarball
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3
  push:
    branches:
      - main
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  packaged_tarball:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: packaged_tarball
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: packaged_tarball/ports
          key: packaged_tarball-ports-${{matrix.runs-on}}-${{hashFiles('packaged_tarball/ext/packaged_tarball/extconf.rb')}}
      - run: bundle exec rake compile test
        working-directory: packaged_tarball
