name: precompiled
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3
  push:
    branches:
      - main
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  precompiled:
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-latest", "macos-latest", "windows-latest"]
        ruby: ["3.0", "3.1", "3.2", "3.3", "head"]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: precompiled
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - uses: actions/cache@v2
        with:
          path: precompiled/ports
          key: precompiled-ports-${{matrix.runs-on}}-${{hashFiles('precompiled/ext/precompiled/extconf.rb')}}
      - run: bundle exec rake compile test
        working-directory: precompiled

  cruby-package:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: precompiled/ports/archives
          key: archives-ubuntu-${{hashFiles('precompiled/ext/precompiled/extconf.rb')}}
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: precompiled
          ruby-version: "3.2"
          bundler-cache: true
      - run: ./bin/test-gem-build gems ruby
        working-directory: precompiled
      - uses: actions/upload-artifact@v2
        with:
          name: cruby-gem
          path: precompiled/gems
          retention-days: 1

  cruby-install:
    needs: "cruby-package"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        ruby: ["3.0", "3.1", "3.2", "3.3", "head"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: precompiled
          ruby-version: "${{ matrix.ruby }}"
      - uses: actions/download-artifact@v4
        with:
          name: cruby-gem
          path: precompiled/gems
      - run: ./bin/test-gem-install gems
        working-directory: precompiled
        shell: bash

  rcd_image_version:
    runs-on: ubuntu-latest
    outputs:
      rcd_image_version: ${{steps.rcd_image_version.outputs.rcd_image_version}}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: precompiled
          ruby-version: "3.2"
          bundler-cache: true
          bundler: latest
      - id: rcd_image_version
        run: bundle exec ruby -e 'require "rake_compiler_dock"; puts "rcd_image_version=#{RakeCompilerDock::IMAGE_VERSION}"' >> $GITHUB_OUTPUT
        working-directory: precompiled

  cruby-native-package:
    needs: ["rcd_image_version"]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "aarch64-linux"
          - "arm-linux"
          - "arm64-darwin" # github actions does not support this runtime, but let's build anyway
          - "x64-mingw-ucrt"
          - "x64-mingw32"
          - "x86-linux"
          - "x86_64-darwin"
          - "x86_64-linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: precompiled/ports/archives
          key: archives-ubuntu-${{hashFiles('precompiled/ext/precompiled/extconf.rb')}}
      - run: |
          docker run --rm -v $PWD/precompiled:/precompiled -w /precompiled \
            ghcr.io/rake-compiler/rake-compiler-dock-image:${{ needs.rcd_image_version.outputs.rcd_image_version }}-mri-${{ matrix.platform }} \
            ./bin/test-gem-build gems ${{ matrix.platform }}
      - uses: actions/upload-artifact@v2
        with:
          name: "cruby-${{ matrix.platform }}-gem"
          path: precompiled/gems
          retention-days: 1

  cruby-linux-install:
    needs: ["cruby-native-package"]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "aarch64-linux"
          - "arm-linux"
          - "x86-linux"
          - "x86_64-linux"
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        include:
          # declare docker platform for each platform
          - { platform: aarch64-linux, docker_platform: "--platform=linux/arm64/v8" }
          - { platform: arm-linux, docker_platform: "--platform=linux/arm/v7" }
          - { platform: x86-linux, docker_platform: "--platform=linux/386" }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cruby-${{ matrix.platform }}-gem
          path: precompiled/gems
      - run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v $PWD/precompiled:/precompiled -w /precompiled \
            ${{ matrix.docker_platform }} ruby:${{ matrix.ruby }} \
            ./bin/test-gem-install gems

  cruby-x86_64-musl-install:
    needs: ["cruby-native-package"]
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: ubuntu-latest
    container:
      image: "ruby:${{matrix.ruby}}-alpine"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cruby-x86_64-linux-gem
          path: precompiled/gems
      - run: apk add bash
      - run: ./bin/test-gem-install gems
        working-directory: precompiled

  cruby-x86_64-darwin-install:
    needs: ["cruby-native-package"]
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
      - uses: actions/download-artifact@v4
        with:
          name: cruby-x86_64-darwin-gem
          path: precompiled/gems
      - run: ./bin/test-gem-install gems
        working-directory: precompiled

  ## arm64-darwin installation testing is omitted until github actions supports it
  #  cruby-arm64-darwin-install:
  #    ...

  cruby-x64-mingw32-install:
    needs: ["cruby-native-package"]
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
      - uses: actions/download-artifact@v4
        with:
          name: cruby-x64-mingw32-gem
          path: precompiled/gems
      - run: ./bin/test-gem-install gems
        working-directory: precompiled

  cruby-x64-mingw-ucrt-install:
    needs: ["cruby-native-package"]
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
      - uses: actions/download-artifact@v4
        with:
          name: cruby-x64-mingw-ucrt-gem
          path: precompiled/gems
      - run: ./bin/test-gem-install gems
        working-directory: precompiled
