name: system
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3
  push:
    branches:
      - main
      - v*.*.x
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'
    paths: ["system/**/*", ".github/workflows/system.yml"]

jobs:
  system:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3", "3.4", "head"]
        runs-on: ["ubuntu-latest", "macos-13", "windows-latest"]
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          working-directory: system
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
          mingw: "libyaml" # windows
          apt-get: "libyaml-dev" # linux
          brew: "libyaml" # macos
      - run: bundle exec rake compile test
        working-directory: system
